CREATE TABLE public.fruits (
	id serial4 NOT NULL,
	"name" varchar NOT NULL,
	avatar varchar NOT NULL,
	detail varchar NOT NULL,
	"valid" varchar DEFAULT 1 NOT NULL,
	price float8 DEFAULT 0 NOT NULL,
	CONSTRAINT fruits_pk PRIMARY KEY (id)
);


INSERT INTO public.fruits (name,avatar,detail,"valid",price) VALUES
	 ('mango','https://images.pexels.com/photos/918643/pexels-photo-918643.jpeg?auto=compress&cs=tinysrgb&w=600','Mangoes are tropical fruits known for their delicious flavor and vibrant appearance. They have a large, oval or kidney-shaped form with a smooth, slightly bumpy skin that can range in color from green to yellow, orange, or a combination of these. The flesh of a mango is typically soft, juicy, and sweet, with a unique and delightful taste. It is highly fragrant, adding to its appeal.','1',0.0),
	 ('apricot','https://images.pexels.com/photos/209416/pexels-photo-209416.jpeg?auto=compress&cs=tinysrgb&w=600','Apricots are small, oval-shaped fruits with a smooth and velvety skin. They have a lovely orange or yellow color when ripe. The flesh of an apricot is tender and sweet, with a hint of tartness, offering a delicious and unique flavor.','1',0.0),
	 ('grape','https://images.pexels.com/photos/708777/pexels-photo-708777.jpeg?auto=compress&cs=tinysrgb&w=600','Grapes are a widely loved and popular fruit. They come in various shapes, sizes, and colors, such as purple, green, red, and black. Grapes have a smooth and shiny skin that encloses a juicy and sweet or sometimes slightly tart flesh.','1',0.0),
	 ('orange','https://images.pexels.com/photos/2288683/pexels-photo-2288683.jpeg?auto=compress&cs=tinysrgb&w=600','Oranges are round and typically medium-sized fruits. They have a bright, vibrant orange-colored peel that is relatively easy to peel off. The flesh inside is segmented and juicy, with a sweet and tangy flavor that is very refreshing.','1',0.0),
	 ('pear','https://images.pexels.com/photos/2987077/pexels-photo-2987077.jpeg?auto=compress&cs=tinysrgb&w=600','Pears are a kind of delicious and nutritious fruit. They usually have a pear-shaped appearance with a smooth and thin skin. The color of the skin can range from green to yellow or brown, depending on the variety.','1',0.0),
	 ('lemon','https://images.pexels.com/photos/161573/background-water-breakfast-bright-161573.jpeg?auto=compress&cs=tinysrgb&w=600','Lemons are small, oval-shaped fruits with a bright yellow color. They have a distinctively tart and acidic flavor.','1',0.0),
	 ('tomato','https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1','A tomato is a widely known and commonly used fruit/vegetable. It is usually spherical or oval in shape, with a smooth and shiny skin that can range in color from bright red to various shades of pink, orange, or even green when unripe. The flesh inside is juicy and has a slightly sweet and tart flavor. Tomatoes are highly versatile and are used in a wide variety of culinary preparations, such as in salads, sauces, soups, and as a topping for pizzas. They are rich in vitamins and antioxidants, making them a healthy addition to any diet.','1',0.0),
	 ('strawberry','https://images.pexels.com/photos/1231023/pexels-photo-1231023.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1','A strawberry is a small, sweet and delicious fruit. It has a bright red color and a distinctive shape with tiny seeds on its surface. The texture is soft and juicy. Strawberries have a wonderful flavor that is a combination of sweet and slightly tart. They are often enjoyed fresh on their own or used in various desserts like cakes, ice creams, and smoothies. Strawberries are also popular in fruit salads. They are not only tasty but also rich in vitamins and antioxidants, which are beneficial for health.','1',0.0),
	 ('pinneapple','https://images.pexels.com/photos/139258/pexels-photo-139258.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1','A pineapple is a tropical fruit with a unique appearance. It has a rough, spiky exterior that is usually golden-yellow in color. The shape is somewhat cylindrical. When cut open, the inside reveals a juicy, sweet and slightly tangy flesh that is a pale yellow or orange color. The flavor of a pineapple is distinct and delicious, a combination of sweet and tart notes. It is commonly used in juices, smoothies, and as a topping for various desserts. Pineapples are also enjoyed on their own as a refreshing snack. They are rich in vitamins and enzymes that offer certain health benefits.','1',0.0),
	 ('banana','https://images.pexels.com/photos/61127/pexels-photo-61127.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1','Bananas are elongated, curved fruits with a yellow peel when ripe. They have a soft and sweet flesh inside. Bananas are one of the most popular fruits globally, known for their convenience and portability. They are a great source of energy as they contain natural sugars like glucose, fructose, and sucrose. Additionally, they offer essential nutrients such as potassium, vitamin B6, and dietary fiber. Bananas can be eaten on their own as a quick and healthy snack, or used in a variety of recipes, including smoothies, desserts, and baked goods. They are relatively easy to store and transport, making them accessible and widely consumed. Whether eaten raw or incorporated into different dishes, bananas are a beloved and versatile fruit.','1',0.0);
INSERT INTO public.fruits (name,avatar,detail,"valid",price) VALUES
	 ('blueberry','https://images.pexels.com/photos/1153655/pexels-photo-1153655.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1','Blueberries are small, round berries with a deep blue color and a smooth surface. They have a sweet and slightly tart flavor, making them a favorite among many people. Blueberries are rich in antioxidants, vitamins, and minerals, which offer numerous health benefits. They are often used in various culinary applications, such as in desserts like pies, cakes, and muffins, or eaten fresh as a healthy snack. The bushes that produce blueberries are found in many parts of the world and are harvested during the summer months. Blueberries are not only delicious but also highly nutritious, making them a great addition to a balanced diet.','1',30.0),
	 ('apple','https://images.pexels.com/photos/672101/pexels-photo-672101.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1','Apple is a very common and beloved fruit. It is round and lovely, with rich and diverse colors such as red, green, or yellow, and its epidermis is smooth and full of texture. Holding it in hand, you can feel its heavy weight. Taking a bite, it is either refreshingly crispy with juices gushing out and carrying the natural sweetness; or it has a dense texture with a hint of unique fruity aroma in the sweetness. Apple is not only delicious but also rich in various nutrients, providing a boost to people''s health. Whether it is enjoyed directly as a daily snack or processed into juice, jam, salad, etc., it can all show its unique charm and become a frequent guest on people''s tables, occupying an important position in the fruit world.','1',99.0),
	 ('pomegranate','https://images.pexels.com/photos/1435735/pexels-photo-1435735.jpeg?auto=compress&cs=tinysrgb&w=600','Pomegranate is a fascinating fruit. It has a unique appearance with a thick and hard rind that is often a bright red color. When you cut it open, you will be amazed by the numerous shiny and juicy arils inside, like beautiful red rubies. The taste of pomegranate is a delightful combination of sweet and tart, offering a refreshing and distinct flavor. It is not only delicious but also rich in antioxidants and nutrients. Pomegranate can be enjoyed on its own, added to salads or used to make refreshing juices. It truly is a wonderful fruit that brings both pleasure and health benefits. ','1',0.0),
	 ('lemon','https://images.pexels.com/photos/1414122/pexels-photo-1414122.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1','Lemons are fascinating fruits. They have a vibrant yellow color that catches the eye. Their shape is oval, and they have a firm texture. Lemons are renowned for their distinctively tart and acidic flavor, which gives them a unique identity. They are extremely versatile and play a crucial role in cooking and beverages. They can be used to add a zesty flavor to various dishes, like fish and salads, or to make refreshing lemonades and cocktails. Lemons are also a great source of vitamin C and other beneficial compounds, which are important for maintaining good health, such as aiding in digestion and supporting the immune system. Additionally, the aroma of lemons is fresh and invigorating, and they are often used in aromatherapy and for making scented products. Whether it''s for enhancing the taste of food or for their potential health benefits, lemons are truly a remarkable fruit.','1',10.899999618530273),
	 ('watermelon','https://images.pexels.com/photos/59830/melons-water-melons-fruit-green-59830.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1','Watermelons are truly remarkable fruits. They have a large, round or oval shape and a thick, green rind. The inside is filled with juicy, sweet, and refreshing red or pink flesh, speckled with black seeds. Watermelons are known for their delicious taste, which is a perfect combination of sweetness and a hint of coolness. They are extremely popular during the summer months as they provide a great way to quench thirst and cool down. Not only are they delicious to eat on their own, but they can also be used in a variety of recipes, such as fruit salads, smoothies, and even as an ingredient in some desserts. Watermelons are also a good source of vitamins and minerals, like vitamin C and potassium, which are beneficial for overall health. Their large size makes them great for sharing with friends and family, and they are often a staple at picnics and gatherings. Whether sliced up and enjoyed fresh or incorporated into different dishes, watermelons are a beloved fruit that brings joy and satisfaction.','1',1.9900000095367432),
	 ('watermelon','https://images.pexels.com/photos/59830/melons-water-melons-fruit-green-59830.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1','xxx','0',1.9900000095367432);
